languageCode: "en-gb"
uglyURLs: false
title: "COAR Notify Documentation"
theme: "coar_notify"
enableRobotsTXT: true
#disableKinds: ["RSS","taxonomy","taxonomyTerm"]
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
blackfriday:
  smartypants: false
  smartDashes: false
  extensionsmask: [ "autolink" ] #disables these extensions
disablePathToLower: true
taxonomies:
  tag: "tags"
  status: "status"
outputs:
  page: [ html,json ]

#outputFormats:
#  JsonLdFormat:
#    baseName: index
#    isPlainText: false
#    mediaType: application/ld+json



params:
  "@context":
    notify:
      name: "Notify"
      uri: "http://purl.org/coar/notify"
    as2:
      name: "Activity Streams 2.0"
      uri: "https://www.w3.org/ns/activitystreams"
  actors:
    generic-person:
      "id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "type": "Person"
    author:
      "id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "type": "Person"
    reviewer:
      "id": "https://isni.org/isni/0000000122832703"
      name: "H G Wells"
      "type": "Person"
    reviewer-2:
      "id": "https://isni:org/isni/00000001214005623"
      name: "Jules Verne"
      "type": "Person"
    generic-organisation:
      "id": "https://some-organisation.org"
      name: "Some Organisation"
      "type": "Organization"
    research-organisation:
      "id": "https://research-organisation.org"
      name: "Research Organisation"
      "type": "Organization"
    generic-service:
      "id": "https://generic-service.com"
      name: "Generic Service"
      "type": "Service"
    review-service:
      "id": "https://review-service.com"
      name: "Review Service"
      "type": "Service"
    endorsement-service:
      "id": "https://endorsement-service.com"
      name: "Endorsement Service"
      "type": "Service"
    overlay-journal:
      "id": "https://overlay-journal.com"
      name: "Overlay Journal"
      "type": "Service"
    aggregation-service:
      "id": "https://aggregator-service.org"
      name: "Aggregation Service"
      "type": "Service"
  systems:
    generic-organisation:
      "id": "https://some-organisation.org/system"
      "type": "Service"
      "inbox": "https://some-organisation.org/system/inbox/"
    generic-service:
      "id": "https://generic-service.com/system"
      "type": "Service"
      "inbox": "https://generic-service.com/system/inbox/"
#    generic-origin-system:
#      "id": "https://origin-system.org"
#      "type": "Service"
#      "inbox": "https://origin-system.org/inbox/"
#    generic-target-system:
#      "id": "https://target-system.org"
#      "type": "Service"
#      "inbox": "https://target-system.org/inbox/"
    repository:
      "id": "https://research-organisation.org/repository"
      "type": "Service"
      "inbox": "https://research-organisation.org/repository/inbox/"
    review-service:
      "id": "https://review-service.com/system"
      "type": "Service"
      "inbox": "https://review-service.com/system/inbox/"
    overlay-journal:
      "id": "https://overlay-journal.com/system"
      "type": "Service"
      "inbox": "https://overlay-journal.com/system/inbox/"
    aggregation-service:
      "id": "https://aggregator-service.org/system"
      "type": "Service"
      "inbox": "https://aggregator-service.org/system/requests/inbox/"
  objects: # also used for 'context' since the context is always something that may have been used as an object in these docs.
    generic-object-repository:
      "id": "https://some-organisation.org/resource/0021"
      "type": "Document"
      "ietf:cite-as": "https://doi.org/10.4598/12123487"
    generic-object-service:
      "id": "https://generic-service.com/resource/1234"
      "type": "Document"
      "ietf:cite-as": "https://doi.org/10.9357/123003"
    preprint:
      "id": "https://research-organisation.org/repository/preprint/201203/421/"
      "type": "sorg:AboutPage"
      "ietf:cite-as": "https://doi.org/10.5555/12345680"
      url:
        "id": "https://research-organisation.org/repository/preprint/201203/421/content.pdf"
        "type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    submission:
      "id": "https://overlay-journal.com/submissions/00001/"
      "type": "sorg:AboutPage"
      url:
        "id": "https://overlay-journal.com/submissions/00001/files/content.pdf"
        "type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    review:
      "id": "https://review-service.com/review/geo/202103/0021"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
#      "coar-notify:reviews":
#        "id": "https://repository.org/preprint/201203/421/"
#        "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "journal-review":
      "id": "https://overlay-journal.com/reviews/000001/00001"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
#      "coar-notify:reviews":
#        "id": "https://repository.org/preprint/201203/421/"
#        "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "repository-review":
      "id": "https://research-organisation.org/repository/review/00001"
      "type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/000001"
#      "coar-notify:reviews":
#        "id": "https://repository.org/preprint/201203/421/"
#        "ietf:cite-as": "https://doi.org/10.5555/12345680"
    endorsement:
      "id": "https://overlay-journal.com/articles/00001/"
      "type": [ "Page","sorg:WebPage" ]
      "ietf:cite-as": "https://overlay-journal.com/articles/00001/"
#      "coar-notify:endorses":
#        "id": "https://repository.org/preprint/201203/421/"
#        "ietf:cite-as": "https://doi.org/10.5555/12345680"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
